### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mitzie92** [phinocio/loadorderlibrary#108]
I've been using this for a while but today when I went to login, there was no response. Tried to create new account and still no response. Just kept asking for my info.
I see  the home page has changed. This might have something to do with it.
Using Windows 10 and Chrome

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by phinocio** [comment]
Likely due to cookies from the prior design still being set and conflicting with the API, resulting in the API failing to actually log in a user, try clearing cookies and logging in again.

I plan to add a proper error for this tomorrow as it doesn't seem to currently show any kind of error

**Comment by mitzie92** [comment]
This worked, tha

**Comment by phinocio** [comment]
I believe this should be fixed. If anyone else comes across this issue and is still experiencing it, please create an issue on https://github.com/phinocio/loadorderlibrary-frontend repo as I'm going to archive this repo soon.
