### ISSUE TITLE
SkyrimCustom.ini (from MO2 profile) is not valid

### ISSUE THREAD

**Issue by Meridiano** [phinocio/loadorderlibrary#40]
When I try to upload SkyrimCustom.ini file from my MO2 profile I get message "SkyrimCustom.ini is not valid. If you believe this is wrong, contact Phin." There is no much info inside, but you may be interested in this unexpected behavior. File included - [SkyrimCustom.zip](https://github.com/phinocio/loadorderlibrary/files/6135863/SkyrimCustom.zip).

**Comment by phinocio** [comment]
At the moment part of file validation is making sure files have >= 5 lines, this file has 3. Though it's clearly a valid file. I'm going to change the limit to >= 1 line

**Comment by phinocio** [comment]
Fixed in v2.3.0 - Minimum number of lines has been decreased to 1.
